---
- name: install httpd server
  hosts: all
  tasks:
    - name: install httpd
      package:
        name: httpd
        state: present
    #- name: Run semanage command
      #command: semanage port -a -t http_port_t -p tcp 82
      #become: yes
    - name: start and enable firewalld
      service:
        name: firewalld
        state: started
        enabled: yes
    - name: add service in firewalld
      firewalld:
        service: http
        state: enabled
        permanent: true
        immediate: true     
      
    - name: create index.html
      copy:
        content: "hello world"
        dest: /var/www/html/index.html
    - name: restart httpd
      service:
        name: httpd
        state: started
        enabled: yes 
      

